app:
  datasource:
    postgres:
      port: 5432
      username: postgres
      password: mypsql
      host: localhost
      databaseName: springbootdb
      jdbc-url: jdbc:postgres://${app.datasource.postgres.host}:${app.datasource.postgres.port}/${app.datasource.postgres.databaseName}